// carousel
export const FETCH_TOP_PRODUCTS_LIST_REQUEST = 'FETCH_TOP_PRODUCTS_LIST_REQUEST'
export const FETCH_TOP_PRODUCTS_LIST_SUCCESS = 'FETCH_TOP_PRODUCTS_LIST_SUCCESS'
export const FETCH_TOP_PRODUCTS_LIST_FAILURE = 'FETCH_TOP_PRODUCTS_LIST_FAILURE'
export const FETCH_TOP_PRODUCTS_REQUEST = 'FETCH_TOP_PRODUCTS_REQUEST'
export const FETCH_TOP_PRODUCTS_SUCCESS = 'FETCH_TOP_PRODUCTS_SUCCESS'
export const FETCH_TOP_PRODUCTS_FAILURE = 'FETCH_TOP_PRODUCTS_FAILURE'

// cart

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const CLEAR_CART = 'CLEAR_CART'

// categories

export const SET_CATALOG_FROM_DB = 'SET_CATALOG_FROM_DB'
export const FETCH_CATALOG_REQUEST = 'FETCH_CATALOG_REQUEST'
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS'
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE'
export const CATALOG_LOCATION = 'CATALOG_LOCATION'

// comments

export const SEND_COMMENT = 'SEND_COMMENT';
export const POST_COMMENTS_REQUEST = 'POST_COMMENTS_REQUEST';
export const GET_PRODUCT_COMMENTS = 'GET_PRODUCT_COMMENTS';
export const RESET_COMMENTS_LIST = 'RESET_COMMENTS_LIST';

// current-product
export const CURRENT_PRODUCT = 'CURRENT_PRODUCT'

// favorites

export const UPDATE_FAVORITES_SUCCESS = 'UPDATE_FAVORITES_SUCCESS';
export const CLEAR_FAVORITES = 'CLEAR_FAVORITES';
export const SET_FAVORITES_FROM_DB = 'SET_FAVORITES_FROM_DB'

// filter

export const GET_FILTER_PRODUCTS = 'GET_FILTER_PRODUCTS'
export const FETCH_FILTER_PARAMS_SUCCESS = 'FETCH_FILTER_PARAMS_SUCCESS'
export const FILTER_TYPE = 'FILTER_TYPE'
export const FILTER_SORT = 'FILTER_SORT'
export const FILTER_INCREASE_PAGE = 'FILTER_INCREASE_PAGE'
export const RESET_FILTERS = 'RESET_FILTERS'

// load-data

export const FETCH_LOAD_REQUEST = 'FETCH_LOAD_REQUEST'
export const FETCH_LOAD_RESPONSE = 'FETCH_LOAD_RESPONSE'

// notification

export const OPEN_NEW_NOTIFICATION = 'OPEN_NEW_NOTIFICATION'
export const ClOSE_NOTIFICATION = 'ClOSE_NOTIFICATION'

// password-validation

export const INVALID_PASSWORD_TRUE = 'INVALID_PASSWORD_TRUE'
export const INVALID_PASSWORD_FALSE = 'INVALID_PASSWORD_FALSE'

// products

export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_MORE_PRODUCTS_SUCCESS = 'FETCH_MORE_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'
export const SORTING_PRODUCTS = 'SORTING_PRODUCTS'
export const RESET_SORTING = 'RESET_SORTING'

// slides

export const GET_MAIN_SLIDES = 'GET_MAIN_SLIDES'

// sorting

export const SORT_CARDS = 'SORT_CARDS'

// user

export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_CUSTOMER_DATA_SUCCESS = 'FETCH_CUSTOMER_DATA_SUCCESS'
export const ENTER_REGISTRATION_PAGE = 'ENTER_REGISTRATION_PAGE'
export const LEAVE_REGISTRATION_PAGE = 'LEAVE_REGISTRATION_PAGE'
export const FETCH_CUSTOMER_DATA_FAILURE = 'FETCH_CUSTOMER_DATA_FAILURE'
export const SET_CUSTOMER_DATA_FROM_DB = 'SET_CUSTOMER_DATA_FROM_DB'

// search

export const STORE_SEARCH_VALUE = 'STORE_SEARCH_VALUE'
